### ISSUE TITLE
IC Trust acknowledgement on issue archive

### ISSUE THREAD

**Issue by lsproc** [FelixOnline/v2#2]
It was a condition of the funding for digitising the felix archive that the IC Trust is given an acknowledgement on issue archive pages. We get told off about this every time we redesign the site so it is important to make sure we do this for the new site.

**Comment by tlfrd** [comment]
So will copying the acknowledgement on the current site:
``` The issue archive was made possible through kind donations from Imperial College Union and the IC Trust. ``` be enough?

**Comment by lsproc** [comment]
Yep!
