### ISSUE TITLE
Issue archive does not show any pdfs when viewing a year

### ISSUE THREAD

**Issue by lsproc** [FelixOnline/v2#3]
E.g. on http://felixonline.co.uk/publications/felix/2017/

**Comment by charlieegan3** [comment]
Hi, thanks for letting me know. I'm not subscribed to the repo and only spotted this issue now.

We're still working out some things to do with getting the site deploying automatically. In the meantime we're juggling felixonline.co.uk and the preview site URLs which make things a bit of a fiddle at times.

Thanks again.
